targets:
  $default:
    builders:
      drift_dev:
        enabled: true
        options:
          sql:
            dialect: sqlite
        generate_for:
          - lib/core/database/**.dart
      json_serializable:
        enabled: true
        generate_for:
          - lib/**.dart
      freezed:
        enabled: true
        generate_for:
          - lib/**.dart